name: alpr_flutter_app
description: A Flutter Android app for automatic license plate recognition using OpenALPR

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Camera functionality
  camera: ^0.10.5+9
  permission_handler: ^12.0.1
  
  # File system operations
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Image processing
  image: ^4.1.3
  
  # JSON handling for OpenALPR results
  json_annotation: ^4.8.1
  
  # HTTP requests (for potential future features)
  http: ^1.1.0
  
  # Firebase and Authentication
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2
  
  # State management
  provider: ^6.1.1
  
  # Production readiness
  logger: ^2.0.2+1
  firebase_crashlytics: ^4.2.1
  firebase_analytics: ^11.3.3
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # OpenALPR configuration files
    - assets/runtime_data/