name: tiny_whisper_tester
description: A Flutter app for testing Whisper Tiny models offline on Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # HTTP requests for model download
  http: ^1.1.0
  dio: ^5.3.2
  
  # Audio recording
  record: ^6.1.1
  permission_handler: ^12.0.1
  
  
  # File system operations
  path_provider: ^2.1.1
  
  # ML inference - Speech Recognition
  speech_to_text: ^7.0.0  # Production-ready live speech recognition
  sherpa_onnx: ^1.10.41  # Offline ONNX model support
  # whisper_ggml: ^1.5.0  # Android build issues
  # flutter_pytorch_lite: ^0.1.0+3  # Temporarily disabled for Android build
  
  # Translation - Language Detection and Translation
  google_mlkit_translation: ^0.12.0  # Offline translation with 50+ languages
  google_mlkit_language_id: ^0.10.0  # Language detection
  
  # On-device LLM inference for summarization (placeholder)
  # tflite_flutter: ^0.10.4  # TensorFlow Lite for Flutter - temporarily disabled due to compatibility issues
  # Note: For Gemma models, we'll need to use TensorFlow Lite with custom delegates
  
  # Audio processing
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/