name: tiny_whisper_tester
description: A Flutter app for testing Whisper Tiny models offline on Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # HTTP requests for model download
  http: ^1.1.0
  dio: ^5.3.2
  
  # Audio recording
  record: ^6.1.1
  permission_handler: ^12.0.1
  
  # File system operations
  path_provider: ^2.1.1
  
  # ML inference - Whisper ASR
  # whisper_ggml: ^1.5.0  # Temporarily disabled for Android build
  # flutter_pytorch_lite: ^0.1.0+3  # Temporarily disabled for Android build
  
  # Audio processing
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/models/